apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
  labels:
    app: sara-app
spec:
  replicas: 2 #The number of pods to be created in the Kubernetes cluster for the application container
  selector:
    matchLabels:
      app: sara-app
  template:
    metadata:
      labels:
        app: sara-app 
    spec:
      containers:
      - name: sara-app #The name of the application container
        image: saravana4285/CICD-APP-DEMO:latest #The Docker image for building the  application container
        ports:
        - containerPort: 80 #The port for the application   container
